language:
   - cpp

# container based   
sudo: false

# add newer compilers
addons:
    apt:
        sources:
            #- llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            #- clang-3.7
            - g++-5
            - gcc-5
            - libboost-test-dev

script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - mkdir build && cd build
    - cmake ..
    - make check
